version: '3.8'

services:
  skateswap-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map to port 8080 instead of 80
    volumes:
      - ./src:/app/src # For development - watch source changes
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # For easier nginx config updates
    depends_on:
      - skateswap-backend
    restart: unless-stopped

  skateswap-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=mysql://root:b6fmvf9k@usw.sealos.io:49708/react_template
      - DB_HOST=usw.sealos.io
      - DB_PORT=49708
      - DB_USER=root
      - DB_PASSWORD=b6fmvf9k
      - DB_NAME=react_template
      - JWT_SECRET=your_jwt_secret_key_here
    restart: unless-stopped
